pnpm改为npm, 否则报错(error TS2583: Cannot find name 'Map')
Running "ts:commonjs" (ts) task
TypeScript cannot use inlineSourceMap and sourceMap together.  Ignoring sourceMap.
Compiling...
Using tsc v3.9.10
node_modules/.pnpm/@types+d3-array@1.2.12/node_modules/@types/d3-array/index.d.ts(269,93): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
node_modules/.pnpm/@types+d3-array@1.2.12/node_modules/@types/d3-array/index.d.ts(282,4): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

>> 2 non-emit-preventing type warnings  
>> Error: tsc return code: 2
Warning: Task "ts:commonjs" failed. Use --force to continue.